#apiVersion: v1
#kind: Service
#metadata:
#  name: hello-world-deployment-85dfb9b8db-wr5zp
#spec:
#  selector:
#    app: hello
#  type: NodePort
#  ports:
#    - name: new-service-port
#      port: 80
#      protocol: TCP
#      nodePort: 30747
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: ingress-hosts
#  annotations:
#    ingress.alb.yc.io/subnets: e9bksm3k51463b0ojr5r,e2le1fcjhmk34m3hul0m,b0c67ujvshmushb5genk
#    ingress.alb.yc.io/external-ipv4-address: auto
#    ingress.alb.yc.io/group-name: ingress-group-1
#spec:
#  tls:
#    - hosts:
#        - stocks-analyzer.xyz
#      secretName: yc-certmgr-cert-id-fpqmsrs424g2g154nm54
#  rules:
#    - host: stocks-analyzer.xyz
#      http:
#        paths:
#          - path: /
#            pathType: Prefix
#            backend:
#              service:
#                name: app-service
#                port:
#                  name: http
#
#
#
#
#
##---
##apiVersion: networking.k8s.io/v1
##kind: Ingress
##metadata:
##  name: ingress-hosts
##  annotations:
##    ingress.alb.yc.io/subnets: e9bksm3k51463b0ojr5r,e2le1fcjhmk34m3hul0m,b0c67ujvshmushb5genk
##    ingress.alb.yc.io/external-ipv4-address: auto
##    ingress.alb.yc.io/group-name: ingress-group-1
##spec:
##  tls:
##    - hosts:
##        - stocks-analyzer.xyz
##      secretName: yc-certmgr-cert-id-fpqmsrs424g2g154nm54
##  rules:
##    - host: stocks-analyzer.xyz
##      http:
##        paths:
##          - path: "/api/v1/login"
##            pathType: Prefix
##            backend:
##              service:
##                name: new-hello-app-service
##                port:
##                  number: 80
#
#
##---
##apiVersion: v1
##kind: ConfigMap
##metadata:
##  name: alb-demo-1
##data:
##  nginx.conf: |
##    worker_processes auto;
##    events {
##    }
##    http {
##      server {
##        listen 80 ;
##        location = /_healthz {
##          add_header Content-Type text/plain;
##          return 200 'ok';
##        }
##        location / {
##          add_header Content-Type text/plain;
##          return 200 'Index';
##        }
##        location = /app1 {
##          add_header Content-Type text/plain;
##          return 200 'This is APP#1';
##        }
##      }
##    }
##---
##apiVersion: apps/v1
##kind: Deployment
##metadata:
##  name: alb-demo-1
##  labels:
##    app: alb-demo-1
##    version: v1
##spec:
##  replicas: 2
##  selector:
##    matchLabels:
##      app: alb-demo-1
##  strategy:
##    type: RollingUpdate
##    rollingUpdate:
##      maxSurge: 1
##      maxUnavailable: 0
##  template:
##    metadata:
##      labels:
##        app: alb-demo-1
##        version: v1
##    spec:
##      terminationGracePeriodSeconds: 5
##      volumes:
##        - name: alb-demo-1
##          configMap:
##            name: alb-demo-1
##      containers:
##        - name: hello-world
##          image: cr.yandex/crpt2j4od8cl0kpuvph9/hello:__VERSION__
##          imagePullPolicy: Always
##          ports:
##            - containerPort: 80
##        - name: alb-demo-1
##          image: nginx:latest
##          ports:
##            - name: http
##              containerPort: 80
##          livenessProbe:
##            httpGet:
##              path: /_healthz
##              port: 80
##            initialDelaySeconds: 3
##            timeoutSeconds: 2
##            failureThreshold: 2
##          volumeMounts:
##            - name: alb-demo-1
##              mountPath: /etc/nginx
##              readOnly: true
##          resources:
##            limits:
##              cpu: 250m
##              memory: 128Mi
##            requests:
##              cpu: 100m
##              memory: 64Mi
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: app-service
#spec:
#  type: ClusterIP
#  ports:
#    - name: http
#      port: 80
#      targetPort: http
#      protocol: TCP