#apiVersion: v1
#kind: Namespace
#metadata:
#  name: hello-world
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: hello-world-deployment
#  namespace: hello-world
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: hello
#  template:
#    metadata:
#      namespace: hello-world
#      labels:
#        app: hello
#    spec:
#      containers:
#        - name: hello-world
#          image: cr.yandex/crpvfoog9ul2kkas1que/__VERSION__
#          imagePullPolicy: Always

apiVersion: v1
kind: Namespace
metadata:
  name: blog-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      namespace: default
      labels:
        app: stock
    spec:
      containers:
        - name: stock-container
          image: cr.yandex/crpvfoog9ul2kkas1que/stock:__VERSION__
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: my-nginx
  labels:
    app: stock
spec:
  ports:
    - port: 8181
      protocol: TCP
  selector:
    app: stock
  type: LoadBalancer
